#!/bin/bash
open_beta=0
NFE=1
have_free_function=0
if [ "$NFE" = 1 ];then
if [ -x /LonelyFool_Tools/tools_info/charge_info ];then
  charge_info=`/LonelyFool_Tools/tools_info/charge_info $validation_code LF-T`
else
  charge_info=LF
fi
beta=`cat <<EOF_USER | grep "$charge_info"
beta_user
2655294004 13267556759 41399d
EOF_USER`
if [ ! -z "$beta" ];then
  cat <<EOF_NFE_V > /LonelyFool_Tools/tools_info/NFE_validation
#!/bin/bash
case \$1 in
  \$validation_code)
  ;;
  *)
    echo "0"
    exit
  ;;
esac
case \$2 in
  LF-T)
  ;;
  *)
    echo "0"
    exit
  ;;
esac
echo "1"
EOF_NFE_V
chmod 0755 /LonelyFool_Tools/tools_info/NFE_validation
echo "高通boot一键移植" > /boot/NFE
cp -a /tmp/NFE/NFE/NFE_function_script /LonelyFool_Tools/script/NFE_function_script
chmod 0755 /LonelyFool_Tools/script/NFE_function_script
cd /LonelyFool_Tools/tools_info
shc -r -f NFE_validation
rm -rf NFE_validation
rm -rf NFE_validation.x.c
mv NFE_validation.x NFE_validation
chmod 0755 NFE_validation
cd /LonelyFool_Tools/LonelyFool_ROM
fi
fi

if [ "$open_beta" = 1 ];then
  cat <<EOF_NFE_OPEN > /LonelyFool_Tools/tools_info/open_beta
#!/bin/bash
case \$1 in
  \$validation_code)
  ;;
  *)
    echo "0"
    exit
  ;;
esac
case \$2 in
  LF-T)
  ;;
  *)
    echo "0"
    exit
  ;;
esac
echo "1"
EOF_NFE_OPEN
chmod 0755 /LonelyFool_Tools/tools_info/open_beta
echo "公测功能" > /boot/NFE
cp -a /tmp/NFE/NFE/NFE_function_script /LonelyFool_Tools/script/NFE_function_script
chmod 0755 /LonelyFool_Tools/script/NFE_function_script
cd /LonelyFool_Tools/tools_info
shc -r -f open_beta
rm -rf open_beta
rm -rf open_beta.x.c
mv open_beta.x open_beta
chmod 0755 open_beta
cd /LonelyFool_Tools/LonelyFool_ROM
fi



if [ "$have_free_function" = 1 ];then
cat <<EOF_H > /LonelyFool_Tools/tools_info/have_free_function
#!/bin/bash
case \$1 in
  \$validation_code)
  ;;
  *)
    exit
  ;;
esac
case \$2 in
  LF-T)
  ;;
  *)
    exit
  ;;
esac
cat <<EOF
charge_t
EOF
EOF_H
cd /LonelyFool_Tools/tools_info
shc -r -f have_free_function
rm -rf have_free_function
rm -rf have_free_function.x.c
mv have_free_function.x have_free_function
chmod 0755 have_free_function
cd /LonelyFool_Tools/LonelyFool_ROM
fi




