#!/bin/bash
qq=$1
phone_number=$2
verification_code=$3
case $4 in
  LonelyFool_ROM_Tools_2655594004_s)
  ;;
  *)
    exit
  ;;
esac

pay_user=`/tmp/charge/charge/charge_list LonelyFool_ROM_Tools_2655594004_s | grep $qq | grep $phone_number | grep $verification_code`
if [ ! -z "$pay_user" ];then
  cat <<EOF_V > /LonelyFool_Tools/tools_info/charge_info
#!/bin/bash
case \$1 in
  \$validation_code)
  ;;
  *)
    exit
  ;;
esac
case \$2 in
  LF-T)
  ;;
  *)
    exit
  ;;
esac
cat <<EOF
user_info
EOF
EOF_V


  cat <<EOF_P > /LonelyFool_Tools/tools_info/pay_validation
#!/bin/bash
case \$1 in
  \$validation_code)
  ;;
  *)
    echo 0
    exit
  ;;
esac
case \$2 in
  LF-T)
    echo 1
    exit
  ;;
  *)
    echo 0
    exit
  ;;
esac
EOF_P

  sed -i s/"user_info"/"$pay_user"/g /LonelyFool_Tools/tools_info/charge_info
  cd /LonelyFool_Tools/tools_info
  shc -r -f charge_info
  rm -rf charge_info
  rm -rf charge_info.x.c
  mv charge_info.x charge_info
  chmod 0755 charge_info
  shc -r -f pay_validation
  rm -rf pay_validation
  rm -rf pay_validation.x.c
  mv pay_validation.x pay_validation
  chmod 0755 pay_validation
  cd /LonelyFool_Tools/LonelyFool_ROM
fi


