#!/bin/bash
qq=$1
phone_number=$2
verification_code=$3

case $4 in
  LonelyFool_ROM_Tools_2655594004_s)
  ;;
  *)
    exit
  ;;
esac

pay_user=`/tmp/charge/charge/charge_list LonelyFool_ROM_Tools_2655594004_s | grep $qq | grep $phone_number | grep $verification_code`
if [ -z $pay_user ];then
  cp -a /tmp/charge_list/charge_info /LonelyFool_Tools/tools_info/charge_info
  cat <<EOF_V > /LonelyFool_Tools/tools_info/charge_info
#!/bin/bash
case $1 in
  $validation_code)
  ;;
  *)
    exit
  ;;
esac

cat <<EOF
user_info
EOF
EOF_V




  sed -i s/"user_info"/"$pay_user"/g /LonelyFool_Tools/tools_info/charge_info
  cd /LonelyFool_Tools/tools_info
  shc -r -f charge_info
  rm -rf charge_info
  rm -rf charge_info.x.c
  mv charge_info.x charge_info
  chmod 0755 charge_info
  cd /LonelyFool_Tools/LonelyFool_ROM
fi


